Udocker cvmfs
virtual-imaging-platform/VIP-portal pull request #346
Opened 2022-06-09 13:55 UTC by SandeshPatilCreatis

1. Added support for udocker
2. Added support for CVMFS

2022-06-13 12:41 UTC, camarasu requested changes

2022-06-13 12:41 UTC, camarasu commented on vip-portal/src/main/resources/vm/wrapper.vm
> +  for d in /cvmfs/biomed.egi.eu/vip/udocker/containers/*/ ; do mkdir containers/$(basename "${d%/}") && ln -s "${d%/}"/* containers/$(basename "${d%/}")/;done
The path "/cvmfs/biomed.egi.eu/vip/udocker/containers" should be en env variable (like BOSH_CVMFS_PATH)

2022-06-22 12:02 UTC, axlbonnet requested changes

2022-06-22 15:01 UTC, SandeshPatilCreatis commented on vip-portal/src/main/resources/vm/wrapper.vm
> +udocker_function
Changes done and pushed

2022-06-28 08:12 UTC, axlbonnet approved these changes

2022-06-28 08:12 UTC, merged