App login page
virtual-imaging-platform/VIP-portal pull request #357
Opened 2022-06-22 10:16 UTC by alexcornier

Access to the list of applications, classes and groups from the login page without the user being logged in

2022-06-23 12:03 UTC, axlbonnet requested changes

2022-06-23 12:03 UTC, axlbonnet commented on vip-core/src/main/java/fr/insalyon/creatis/vip/core/server/business/VipSessionBusiness.java
> +    }
Maybe we should add a condition on the cookies

2022-06-23 12:03 UTC, axlbonnet commented on vip-core/src/main/java/fr/insalyon/creatis/vip/core/client/view/auth/SignInTab.java
> +                "https://www.creatis.insa-lyon.fr/vip/news.html</a>",20);
Maybe we could improve the formatting.

2022-06-23 12:03 UTC, axlbonnet commented on vip-core/src/main/java/fr/insalyon/creatis/vip/core/server/rpc/AbstractRemoteServiceServlet.java
> +            throw new CoreException("The user has no sysvipSessionBusiness.tem administrator rights.");
typo

2022-06-23 12:03 UTC, axlbonnet commented on vip-core/src/main/java/fr/insalyon/creatis/vip/core/server/rpc/AbstractRemoteServiceServlet.java
> +            logger.info("(Anonymous) " + message);
remove logs

2022-06-23 12:25 UTC, alexcornier commented on vip-application/src/main/java/fr/insalyon/creatis/vip/application/client/ApplicationModule.java
> +                 Logger.getLogger("log").info("test publication module");
Done ✔️

2022-06-23 12:26 UTC, alexcornier commented on vip-application/src/main/java/fr/insalyon/creatis/vip/application/client/view/system/application/ManageApplicationsTab.java
> +        this.setCanClose(true);
Nothing, i removed it ✔️

2022-06-23 12:46 UTC, alexcornier commented on vip-application/src/main/java/fr/insalyon/creatis/vip/application/client/view/system/application/ManageApplicationsTab.java
> +        }
Done ✔️

2022-06-23 13:33 UTC, alexcornier commented on vip-application/src/main/java/fr/insalyon/creatis/vip/application/client/bean/Application.java
> +    public Application(String name, List<String> classes, String owner, String citation, List<String> groups){}
Done ✔️

2022-06-28 07:13 UTC, axlbonnet commented on vip-application/src/main/java/fr/insalyon/creatis/vip/application/client/bean/Application.java
> +    public Application(String name, List<String> classes, String owner, String citation, List<String> groups){}
It is still there.. maybe a merge glitch

2022-06-28 07:13 UTC, axlbonnet commented on vip-core/src/main/java/fr/insalyon/creatis/vip/core/client/view/CoreConstants.java
> +    public static final String HOME_ACTION_SHOW_APPLICATIONS = "SHOW_PPLICATIONS";
It is still there.. maybe a merge glitch

2022-06-28 08:10 UTC, axlbonnet approved these changes

2022-06-28 08:10 UTC, merged