Strip extension
virtual-imaging-platform/VIP-portal pull request #415
Opened 2023-05-11 22:15 UTC by SandeshPatilCreatis

1. Boutiques support stripping the extension of the file. ('path-template-stripped-extensions')
2. But this feature of the boutique schema is not functioning on VIP.
3. It is to remove the extension of the path template (similar to baseline command in bash).

1. descriptor -> xml

    Descriptor key : Mapped to Java class (BoutiquesOutputFile) 2 variables , one for capturing strip extn values and another boolean variable which decide the descriptor contains strip extn or not and defined getter setters for those two variables
    To set value of those 2 variables in BoutiquesOutputFile : Java class : BoutiquesParser method : parseBoutiquesOutputFile and in gasw.vm : to add strip extn value in template tag based on condition

2. xml -> file creation with /without strip extn

    GaswParser : to read strip extn value from xml. if it’s not present in xml then create empty object of Set<String>
    GaswOutputTemplatePart : created a varaible to store value to srip extensions(since there can be multiple extensions we are using Set<String> stripExtensions)
    GaswParser : wherever we create object of GaswOutputTemplatePart class, we pass strip extension value to the constructor.
    GaswParser: method parseOutputTemplat: Inside case : Name , we replace strpextension with blank.(removing strip extensions from i/p file)

2023-06-07 08:43 UTC, axlbonnet requested changes
This is working but I suggest some small improvements.

Also, there are 2 PR mixed in there, the SRM stuff should not be present here. Could you do a new PR, starting from the current develop and containing only  the stripped extensions stuff ?

2023-06-07 08:43 UTC, axlbonnet commented on vip-portal/src/main/resources/vm/gasw.vm
> +#set ($i=$i+1)
I think this line should not be here

2023-06-07 08:43 UTC, axlbonnet commented on vip-portal/src/main/resources/vm/gasw.vm
> +    <template value="$prefix1$dir1/$na1/$value$options1" strip-extension="$outputFile.getPathTemplateStrippedExtensions()"/>
Could you add the `if` to only add the strip-extension part ? Like

```
     <template value="$prefix1$dir1/$na1/$value$options1"
     #if($outputFile.isStripExtension())
          strip-extension="$outputFile.getPathTemplateStrippedExtensions()"
     #end 
    />
```

2023-06-07 08:43 UTC, axlbonnet commented on vip-datamanagement/src/main/java/fr/insalyon/creatis/vip/datamanager/client/bean/ExternalPlatform.java
> +        SRM
SRM stuff should not be in this PR

2023-06-07 08:43 UTC, axlbonnet commented on vip-application/src/main/java/fr/insalyon/creatis/vip/application/client/bean/boutiquesTools/BoutiquesOutputFile.java
> +    private boolean isStripExtension;
This boolean is not necessary.
I prefer you to use a condition on `pathTemplateStrippedExtensions` being not null and not empty in the gasw.vm instead.

2023-06-25 20:22 UTC, closed without merging

2023-06-25 20:23 UTC, SandeshPatilCreatis commented
redundant #421